appmoduleid: 'ccb6a49b-a622-ef11-840b-000d3a840a45'
appmoduleversion: null
clienttype: 4
url: null
description: Provides access to the Resource Scheduling solution
name: Resource Scheduling
uniquename: msdyn_ResourceScheduling

