appmoduleid: 'da8a8afe-1b20-ef11-840b-6045bd5ea018'
appmoduleversion: null
clienttype: 4
url: null
description: Bring your communication channels and build immersive experience with Dynamics 365
name: Channel Integration Framework
uniquename: msdyn_ChannelIntegrationFrameworkApp

