appmoduleid: 'e47e35cb-9435-f011-8c4f-002248b0f955'
appmoduleversion: null
clienttype: 4
url: null
description: Configure and manage your online platform to communicate and collaborate with customers.
name: Portal Management
uniquename: Dynamics365Portals

