appmoduleid: 'bb70ee3e-51a5-f011-bbd2-002248afda59'
appmoduleversion: null
clienttype: 4
url: null
description: Team Member access to Project Operations.
name: Project Operations Team Member
uniquename: msdyn_TimeExpense

