views:
  -
    name: Related Solutions Snapshots
    description: All active Related Solutions Snapshots
    querytype: 8192
    savedqueryid: 'd0525729-ea66-ef11-a670-000d3af43a08'
  -
    name: Related Solutions Snapshot Advanced Find View
    querytype: 1
    savedqueryid: 'c9ef0f7c-2ebd-42ef-b3fd-01338afd5c73'
  -
    name: Related Solutions Snapshots Copilot View
    querytype: 1048576
    savedqueryid: 'c1ba4501-4465-6b2c-3a50-22e1db629d5a'
  -
    name: Quick Find Active Related Solutions Snapshots
    querytype: 4
    savedqueryid: '5740b991-c471-4c4a-a05c-599817484f5e'
  -
    name: Related Solutions Snapshot Lookup View
    querytype: 64
    savedqueryid: 'd79bdede-12e4-4297-85d0-5e5ef3745134'
  -
    name: Related Solutions Snapshot Associated View
    querytype: 2
    savedqueryid: '6b45bb64-8528-40ba-84f1-70ed32c94d2f'
  -
    name: All Related Solutions Snapshots
    querytype: -1
    savedqueryid: '3a4785c1-666b-4397-a3e0-c4f0580f4652'

