views:
  -
    name: Opportunity Advanced Find View
    querytype: 1
    savedqueryid: '00000000-0000-0000-00aa-000000666800'
  -
    name: Opportunity Associated View
    description: Displays information about opportunities in the detail form of any associated record.
    querytype: 2
    savedqueryid: '00000000-0000-0000-00aa-000010001203'
  -
    name: My Open Opportunities
    querytype: -1
    savedqueryid: '00000000-0000-0000-00aa-000010003000'
  -
    name: Open Opportunities
    querytype: -1
    savedqueryid: '00000000-0000-0000-00aa-000010003001'
  -
    name: Opportunities Closing Next Month
    querytype: -1
    savedqueryid: '00000000-0000-0000-00aa-000010003002'
  -
    name: Opportunities Opened Last Week
    querytype: -1
    savedqueryid: '00000000-0000-0000-00aa-000010003003'
  -
    name: Opportunities Opened This Week
    querytype: -1
    savedqueryid: '00000000-0000-0000-00aa-000010003004'
  -
    name: Closed Opportunities
    querytype: -1
    savedqueryid: '00000000-0000-0000-00aa-000010003006'
  -
    name: 'All Opportunities at Risk - Contact left'
    querytype: -1
    savedqueryid: '1c56c2e4-6d3a-e911-8185-000d3a070f2c'
  -
    name: 'My Opportunities at Risk - Contact left'
    querytype: -1
    savedqueryid: '82d441ef-6d3a-e911-8185-000d3a070f2c'
  -
    name: 'Manager - Closed Opportunities [this month]'
    querytype: -1
    savedqueryid: '95b1709c-1e9d-ef11-8a6a-000d3a0a3998'
  -
    name: Opportunities Forecast View
    querytype: -1
    savedqueryid: 'bf649add-6c30-ea11-a813-000d3a5475f7'
  -
    name: 'Manager - Closed Opportunities [last month]'
    description: all closed opportunities won for last month where owning user's manager is you
    querytype: -1
    savedqueryid: '7eb3ec65-1e9d-ef11-8a6a-000d3af4dd88'
  -
    name: Participating Opportunity View
    querytype: 2048
    savedqueryid: 'd601b503-bb1f-e911-817c-000d3af95fa8'
  -
    name: My Closed Opportunities in Current Fiscal Year
    description: Shows opportunities for the current user that are closed for the current fiscal year.
    querytype: -1
    savedqueryid: '31dae384-a86f-df11-986c-00155d2e3002'
  -
    name: Closed Opportunities in Current Fiscal Year
    description: Shows opportunities that are closed for the current fiscal year.
    querytype: -1
    savedqueryid: '9bee7ca3-b068-df11-ae90-00155d2e3002'
  -
    name: All Opportunities
    description: Shows all the opportunities
    querytype: -1
    savedqueryid: 'c6f6fc1b-1b3e-e711-80e1-00155d871bb4'
  -
    name: Opportunities in Current Fiscal Year
    description: 'All the won, lost and open opportunities for the current fiscal year.'
    querytype: -1
    savedqueryid: '5cfca9b8-2d7c-e211-bb35-00155d882402'
  -
    name: Opportunities I Follow
    description: Opportunities that you follow.
    querytype: -1
    savedqueryid: 'b2a4f916-5f90-e011-95ae-00155d9cfa02'
  -
    name: Opportunities Being Followed
    description: Opportunities being followed.
    querytype: -1
    savedqueryid: 'b2a4f916-5f90-e011-95ae-00155d9cfa03'
  -
    name: Won Opportunities
    querytype: -1
    savedqueryid: 'f73a5bef-a782-de11-9ff3-00155da3b012'
  -
    name: Lost Opportunities
    querytype: -1
    savedqueryid: '5bd2527c-a882-de11-9ff3-00155da3b012'
  -
    name: Other deals for a given customer
    querytype: -1
    savedqueryid: 'b050766e-8656-e511-80e6-00155db85301'
  -
    name: Recent Opportunities
    description: Recent Opportunities
    querytype: -1
    savedqueryid: '9c3f7ee8-eca7-e211-9fb6-00155dd0ea05'
  -
    name: My Open Opportunities by Relationship
    querytype: -1
    savedqueryid: 'c6179eaa-6f4e-e611-80be-0024e8469fb9'
  -
    name: My Connections
    description: Shows all active instances of the opportunity that the current user is connected to via an active connection
    querytype: -1
    savedqueryid: 'b69375fb-61ef-433e-a4c2-031856f9a9e5'
  -
    name: My Recent Opportunities
    description: Recently changed opportunities owned by me
    querytype: 8192
    savedqueryid: '2c83cdd6-e454-4e2c-9be5-0588a1db3c44'
  -
    name: Project Service Opportunities I am a member of
    description: Shows all active instances of the opportunity that the current user is member of
    querytype: -1
    savedqueryid: 'b9a38d60-892e-4360-a0f3-0961f7b9acad'
  -
    name: Recent Opportunities For Interaction Centric Form
    querytype: -1
    savedqueryid: '09f55f67-3964-4a94-92e3-25c9d272dc30'
  -
    name: Opportunity Lookup View
    querytype: 64
    savedqueryid: '9eb361b4-67ac-4830-8abf-2d29efbaee2c'
  -
    name: My open opportunities without sequences
    description: Show my open opportunities that aren't connected to a sequence.
    querytype: -1
    savedqueryid: '7f0187b7-a1a7-4a92-ba24-40075a03b7fd'
  -
    name: My Open Project Service Opportunities
    querytype: -1
    savedqueryid: '74f25f3b-4602-4c40-8957-441d8b169927'
  -
    name: Quick Find Open Opportunities
    querytype: 4
    savedqueryid: '3f6d889e-6549-4025-9ce0-4c4103efb6a3'
  -
    name: Project Service Opportunity Lookup View
    querytype: 64
    savedqueryid: 'e75f6924-663f-4237-ae53-5878e83cfd2b'
  -
    name: 'Manager - Created Opportunity [this month]'
    description: All opportunities created this month owned by the team
    querytype: -1
    savedqueryid: '429a67a9-f0a5-ef11-a72d-6045bdf9b92b'
  -
    name: My Closed Project Service Opportunities in Current Fiscal Year
    description: Shows opportunities for the current user that are closed for the current fiscal year.
    querytype: -1
    savedqueryid: '5c8e532e-4d2c-4daf-a09e-68dcc432dd3f'
  -
    name: Lost Project Service Opportunities
    querytype: -1
    savedqueryid: 'a1da34a6-a403-4919-879e-6b3a55fb69c7'
  -
    name: Opportunities I am a member of
    description: Shows all active instances of the opportunity that the current user is member of
    querytype: -1
    savedqueryid: '0fa11297-a5db-446b-89ee-7b0771d1d590'
  -
    name: 'Manager - Created Opportunity from team [this month]'
    description: All opportunities created this month where owning user's has you as a manager
    querytype: -1
    savedqueryid: '85b68807-b89a-ef11-8a6a-7c1e524071bb'
  -
    name: 'Manager - Closed or due [this month]'
    querytype: -1
    savedqueryid: '8481f447-1e9d-ef11-8a6a-7c1e524071bb'
  -
    name: 'Manager - Created Opportunity [last month]'
    description: All opportunities created last month owned by the team
    querytype: -1
    savedqueryid: 'e8cb4f9e-a7a6-ef11-a72d-7c1e524085ab'
  -
    name: Project Service Opportunities Opened Last Week
    querytype: -1
    savedqueryid: '5de5e654-0600-4de0-b958-7e4291f54dd6'
  -
    name: Won Project Service Opportunities
    querytype: -1
    savedqueryid: '7389792d-1e37-40c0-b798-8ff33f78139a'
  -
    name: Project Service deals for a given customer
    querytype: -1
    savedqueryid: '0fffdd8d-9c32-41d7-9717-93b1eddc7f1d'
  -
    name: My Project Service Opportunity Connections
    description: Shows all active instances of the opportunity that the current user is connected to via an active connection
    querytype: -1
    savedqueryid: '6083da56-f65c-4607-b984-b92b770ef3e2'
  -
    name: Project Service Opportunities Opened This Week
    querytype: -1
    savedqueryid: '031c72ea-6bf5-40a7-931f-bf688c94bec1'
  -
    name: My Open Opportunities Scored
    querytype: -1
    savedqueryid: '8a060c3f-edce-4deb-b283-c6773b222f92'
  -
    name: Project Service Opportunities in Current Fiscal Year
    description: 'All the won, lost and open opportunities for the current fiscal year.'
    querytype: -1
    savedqueryid: 'de62f04d-4dc0-426d-a340-d56f09859d28'
  -
    name: All Project Service Opportunities
    description: Shows all the opportunities
    querytype: -1
    savedqueryid: '88a16890-cfe2-4071-ab7c-d6dafc99e1f1'
  -
    name: Segment associated opportunities
    description: Segment associated opportunities
    querytype: 1024
    savedqueryid: '9bf5425f-24f3-4ff0-aa55-e0c96e1b874c'
  -
    name: Recent Project Service Opportunities
    description: Recent Opportunities
    querytype: -1
    savedqueryid: '114e7079-a156-4c03-bca4-e6fff4255085'
  -
    name: Closed Project Service Opportunities
    querytype: -1
    savedqueryid: '005ff139-d4e2-4168-a6cc-ecf380cd9441'
  -
    name: Open Project Service Opportunities
    querytype: -1
    savedqueryid: 'b4952249-bb5c-4b66-acab-eedf01fd0387'
  -
    name: Open opportunities without sequences
    description: Show open opportunities that aren't connected to a sequence.
    querytype: -1
    savedqueryid: '8a3fd1f6-f35c-4295-aac3-ef5cadf28f50'
  -
    name: Closed Project Service Opportunities in Current Fiscal Year
    description: Shows opportunities that are closed for the current fiscal year.
    querytype: -1
    savedqueryid: '185812cc-3075-4dae-a149-ef6e41d76fed'
  -
    name: Project Service Opportunities Closing Next Month
    querytype: -1
    savedqueryid: '99d19c46-138f-45b9-b95d-fbb4035d0b0e'

