appmoduleid: 'f4a277dd-0220-ef11-840b-6045bd5ea018'
appmoduleversion: null
clienttype: 4
url: null
description: 'Discover the latest feature set available in Dataverse with more guidance on when and how to use each capability, and get value from Dataverse faster.'
name: Dataverse Accelerator App
uniquename: cat_DataverseCompanionApp

