appmoduleid: '91ae37a5-0420-ef11-840b-6045bd5ea018'
appmoduleversion: null
clienttype: 4
url: null
description: Configure and manage your online platform to communicate and collaborate with customers.
name: Power Pages Management
uniquename: mspp_PowerPageManagement

