appmoduleid: '51dc05e6-7a23-ef11-840a-0022483e8dfe'
appmoduleversion: null
clienttype: 4
url: null
description: 'Know and engage your customers to orchestrate personalized, real-time customer experiences.'
name: 'Customer Insights - Journeys'
uniquename: msdyncrm_MarketingSMBApp

