appmoduleid: 'afc40e42-2d20-ef11-840b-6045bd5ea018'
appmoduleversion: null
clienttype: 4
url: null
description: 'Multi-session Customer Service with Productivity tools'
name: Customer Service workspace
uniquename: msdyn_CustomerServiceWorkspace

