appmoduleid: 'c748a902-51a5-f011-bbd2-002248afda59'
appmoduleversion: null
clienttype: 4
url: null
description: A combined full featured experience for managing your Projects.
name: Project Operations
uniquename: msdyn_ProjectService

