appmoduleid: '019c1339-3420-ef11-840b-6045bd5ea018'
appmoduleversion: null
clienttype: 4
url: null
description: A simplified admin app that includes a live chat demo.
name: Omnichannel admin center
uniquename: msdyn_CSAdminApp

