appmoduleid: '39e7c089-0f20-ef11-840b-6045bd5ea018'
appmoduleversion: null
clienttype: 4
url: null
description: 'A focused, interactive experience for managing your customer service.'
name: Customer Service Hub
uniquename: Customerservicehub

