appmoduleid: 'd83ac8b0-9c23-ef11-840b-002248b1d264'
appmoduleversion: null
clienttype: 4
url: null
description: A unified experience for your agents interacting across communication channels to deliver an enhanced customer service.
name: Omnichannel for Customer Service
uniquename: OmniChannelEngagementHub

