appmoduleid: 'b8f58883-107b-ef11-ac20-6045bd5f37d7'
appmoduleversion: null
clienttype: 4
url: null
description: View and manage the settings for your environment
name: Power Platform Environment Settings
uniquename: PowerPlatformEnvironmentSettings

