views:
  -
    name: User Advanced Find View
    querytype: 1
    savedqueryid: '00000000-0000-0000-00aa-000000666d00'
  -
    name: Enabled Users
    description: List of Enabled Users.
    querytype: -1
    savedqueryid: '00000000-0000-0000-00aa-000010001019'
  -
    name: Local Business Users
    querytype: -1
    savedqueryid: '00000000-0000-0000-00aa-000010001020'
  -
    name: My Direct Reports
    querytype: -1
    savedqueryid: '00000000-0000-0000-00aa-000010001021'
  -
    name: Subsidiary Users
    querytype: -1
    savedqueryid: '00000000-0000-0000-00aa-000010001023'
  -
    name: Disabled Users
    querytype: -1
    savedqueryid: '00000000-0000-0000-00aa-000010001119'
  -
    name: User Associated View
    querytype: 2
    savedqueryid: '00000000-0000-0000-00aa-000010001212'
  -
    name: 'Pre-Sales Users'
    querytype: -1
    savedqueryid: '429b7db5-3328-ef11-840a-000d3a0a0241'
  -
    name: Bot agents
    description: Bot agents
    querytype: -1
    savedqueryid: '99a522b5-e038-e911-a9aa-000d3a36c3bf'
  -
    name: Supervisors
    querytype: -1
    savedqueryid: 'b702c2d1-1c72-eb11-a812-000d3a374668'
  -
    name: Agents
    querytype: -1
    savedqueryid: '94b84e8f-2772-eb11-a812-000d3a374668'
  -
    name: Administrators
    querytype: -1
    savedqueryid: '27e6c8f8-3972-eb11-a812-000d3a374668'
  -
    name: All
    querytype: -1
    savedqueryid: '07fd7812-3a72-eb11-a812-000d3a374668'
  -
    name: Omnichannel Users
    querytype: -1
    savedqueryid: '30561b8d-8dbd-e811-8149-000d3a45c66e'
  -
    name: Bot Users
    description: Bot Users
    querytype: -1
    savedqueryid: '28890f93-b2cb-e811-a94c-000d3a7083a8'
  -
    name: Users associated with User Profile
    description: Users associated with User Profile
    querytype: -1
    savedqueryid: '1edac89f-2337-e811-8135-000d3af71628'
  -
    name: Team members
    querytype: -1
    savedqueryid: '30ce6879-6b7a-e211-8976-00155d89ac0c'
  -
    name: Users Following
    description: Users following.
    querytype: -1
    savedqueryid: 'e8ac8d63-47ba-e011-b85e-00155d8a2749'
  -
    name: Users Being Followed
    description: Users being followed.
    querytype: -1
    savedqueryid: '0dda4fb7-84bc-e011-b85e-00155d8a2749'
  -
    name: Users I Follow
    description: Users I follow.
    querytype: -1
    savedqueryid: 'b2529a68-5f90-e011-95ae-00155d9cfa02'
  -
    name: Schedulable Users
    querytype: -1
    savedqueryid: '21c2e70e-d51a-e511-80c5-00155db9c701'
  -
    name: Licensed Users
    querytype: -1
    savedqueryid: 'fd58c16f-26a6-ed11-aad1-00224880cd34'
  -
    name: 'Enabled Users - With Manager'
    description: List of Enabled Users.
    querytype: -1
    savedqueryid: 'c40967fb-0945-ef11-a316-002248b09220'
  -
    name: Users with no assigned security roles
    querytype: -1
    savedqueryid: '61289874-49fb-43ff-aff0-00380e820515'
  -
    name: Power Pages Users
    description: List of all power page consumer users
    querytype: -1
    savedqueryid: '1fe05f14-0074-49e3-b55d-0af1fd0a2b85'
  -
    name: Agentic Users
    description: List of all agentic users
    querytype: -1
    savedqueryid: 'caa2cfbe-a5a9-4d0c-b3b8-107fd805df45'
  -
    name: Users Assigned to Mobile Offline Profile
    description: Users who are assigned to a mobile offline profile.
    querytype: -1
    savedqueryid: 'e5d893d1-2b1f-46e5-8ea4-25562567ccce'
  -
    name: Users Who Follow You
    description: Users who follow you.
    querytype: -1
    savedqueryid: '1d482328-ab23-486b-b241-26603d367f4d'
  -
    name: Full Access Users
    querytype: -1
    savedqueryid: 'da675923-da9d-4702-aad6-3207283a5ace'
  -
    name: Activity Sender Users Lookup View
    querytype: 64
    savedqueryid: 'aba981c9-16a2-4dcc-b694-376ae95fa4b0'
  -
    name: 'Users: Influenced Deals That We Won'
    description: Key users who influenced deals that have been won in the last 12 months.
    querytype: -1
    savedqueryid: 'fcf02d37-524a-4332-8ac7-497ef6b739f9'
  -
    name: Users deleted in tenant but exist in the environment
    description: Users deleted in tenant but exist in the environment view
    querytype: -1
    savedqueryid: '19487f2f-8405-4d59-8f8b-4eda98d4f302'
  -
    name: Users in this position
    querytype: -1
    savedqueryid: '31e76b45-bfe7-447e-b4b5-50dc393bcdbe'
  -
    name: Stub Users
    description: Stub Users View
    querytype: -1
    savedqueryid: '490b1410-d231-46b0-b5fa-60017b21ab14'
  -
    name: Disabled users consuming licenses
    querytype: -1
    savedqueryid: '5953249b-2a59-43bf-a94f-6b8cc1f2d245'
  -
    name: All Project Members
    querytype: -1
    savedqueryid: '081081cb-284f-e411-8854-6c3be5a86d28'
  -
    name: Application Users
    querytype: -1
    savedqueryid: '51af2f40-36bb-4198-9b0c-71a986c7c953'
  -
    name: Administrative Access Users
    querytype: -1
    savedqueryid: '862c3cbf-23ff-4eab-b9a9-7b438bac70a9'
  -
    name: All Users
    description: All Users view
    querytype: 2048
    savedqueryid: '5aecef10-d691-4cee-a86f-7bd0fd161f79'
  -
    name: Salespeople Lookup View
    querytype: 64
    savedqueryid: 'bb3cd580-ecfb-4a85-a623-9a109b73815f'
  -
    name: Unassigned Salespeople
    querytype: 64
    savedqueryid: 'aad628c6-f0dd-4d34-b0ed-9a78f9c23a20'
  -
    name: User Lookup View
    querytype: 64
    savedqueryid: 'e88ca999-0b16-4ae9-b6a9-9edc840d42d8'
  -
    name: 'Read-Only Access Users'
    querytype: -1
    savedqueryid: 'af89fdc8-5d83-40b4-988c-a0941579ee9d'
  -
    name: My Connections
    description: Shows all active instances of the user that the current user is connected to via an active connection
    querytype: -1
    savedqueryid: '8dd58e14-0138-47d4-ba2d-a7dc76094d05'
  -
    name: @Me
    description: @Me
    querytype: -1
    savedqueryid: '9c91ff7f-3df9-4aa9-9f00-aaa2beb3192f'
  -
    name: By Me
    description: By Me
    querytype: -1
    savedqueryid: '79ea2cce-4c0d-4de8-a6a4-ab4b2e362937'
  -
    name: Quick Find All Users
    querytype: 4
    savedqueryid: '51a81e33-e44a-485f-a24f-acbe2c978b92'
  -
    name: Soft deleted Users
    description: Soft deleted Users view
    querytype: -1
    savedqueryid: '5fda842a-004b-42b4-a611-b93c2c69667e'
  -
    name: All Salespersons
    description: List of all salespeople in the organization
    querytype: 2
    savedqueryid: '79183c45-0e58-4860-8354-bce2d7a475c9'
  -
    name: 'Salesperson Associated View - By Territories'
    querytype: 2
    savedqueryid: '7669317d-c0f8-4f19-8a4c-c655c40ac68f'
  -
    name: User Invitation Status
    querytype: -1
    savedqueryid: 'd9089eb6-ee9f-4747-8de4-cd664f182c7d'
  -
    name: Active Directory Users
    querytype: 2048
    savedqueryid: '1468f00b-1618-42db-8445-d08a8e487890'
  -
    name: Associated Record Team Members
    querytype: -1
    savedqueryid: 'f79ad170-ae03-4f4c-8132-d4aa08520a0c'
  -
    name: 'Users: Primary Email (Pending Approval)'
    querytype: -1
    savedqueryid: '89939d86-f073-42ba-bfc4-da7999c78825'

