appmoduleid: '685a7b00-c660-f011-bec1-002248b26171'
appmoduleversion: null
clienttype: 4
url: null
description: 'Enable employees to self-serve by searching for knowledge articles and creating cases​.'
name: Customer Service Team Member
uniquename: CustomerServiceTeamMember

