appmoduleid: '69d3c088-2c20-ef11-840b-6045bd5ea018'
appmoduleversion: null
clienttype: 4
url: null
description: A unified app for Copilot Service administration
name: Copilot Service admin center
uniquename: msdyn_CSAdminCenter

