appmoduleid: 'e78f7645-3420-ef11-840b-6045bd5ea018'
appmoduleversion: null
clienttype: 4
url: null
description: A unified and consistent experience for your agents interacting across communication channels to deliver an enhanced customer service
name: Omnichannel Administration
uniquename: msdyn_OCAPP

